import {
  setItem,
  getReference,
  getItem,
  uuid,
  getLastPathname,
  getUrlParam,
  getFileSize,
  encrypt,
  getSlug,
  splitPayment,
  getRandomIndex,
  formatToNumber,
  getPriceInXCurrency,
  getFeeInXCurrency,
  clearLocalStorage,
} from "./utils";

import {
  validateLoginForm,
  validateSignUpForm,
  validateRPForm,
  validateAddressForm,
  validateCreateShopForm,
  validatePaymentForm,
  validateAddProductForm,
} from "./validators";

export {
  setItem,
  getReference,
  getRandomIndex,
  formatToNumber,
  splitPayment,
  getItem,
  uuid,
  clearLocalStorage,
  getSlug,
  encrypt,
  getUrlParam,
  getLastPathname,
  getFileSize,
  getPriceInXCurrency,
  getFeeInXCurrency,
  validateLoginForm,
  validateSignUpForm,
  validateRPForm,
  validateAddressForm,
  validatePaymentForm,
  validateCreateShopForm,
  validateAddProductForm,
};
